# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - depguard
    - paralleltest
    - wsl
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: true
      branch-max-lines: 4
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - dupl
          - err113
          - exhaustruct
          - funlen
          - gosec
          - ireturn
          - revive

formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120
