# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - paralleltest
    - wsl
  settings:
    depguard:
      rules:
        no_test_packages_in_prod_code:
          list-mode: lax
          files:
            - "$all"
            - "!$test"
            - "!**/mocks/**"
            - "!**/testutil/**"
          deny:
            - pkg: github.com/onsi/ginkgo
              desc: Testing libraries are not allowed in production code
            - pkg: github.com/onsi/gomega
              desc: Testing libraries are not allowed in production code
            - pkg: go.uber.org/mock/gomock
              desc: Testing libraries are not allowed in production code
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: true
      branch-max-lines: 4
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - dupl
          - err113
          - exhaustruct
          - funlen
          - gosec
          - ireturn
          - revive

formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120
