// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-gophermart/internal/gophermart/handler (interfaces: BalanceService)
//
// Generated by this command:
//
//	mockgen -typed -destination=../../test/mocks/gophermart/handler/balance_service.go -package=mocks github.com/bq2cd/yp-go-gophermart/internal/gophermart/handler BalanceService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bq2cd/yp-go-gophermart/internal/gophermart/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceService is a mock of BalanceService interface.
type MockBalanceService struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceServiceMockRecorder
	isgomock struct{}
}

// MockBalanceServiceMockRecorder is the mock recorder for MockBalanceService.
type MockBalanceServiceMockRecorder struct {
	mock *MockBalanceService
}

// NewMockBalanceService creates a new mock instance.
func NewMockBalanceService(ctrl *gomock.Controller) *MockBalanceService {
	mock := &MockBalanceService{ctrl: ctrl}
	mock.recorder = &MockBalanceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceService) EXPECT() *MockBalanceServiceMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockBalanceService) GetBalance(ctx context.Context, userID domain.UserID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBalanceServiceMockRecorder) GetBalance(ctx, userID any) *MockBalanceServiceGetBalanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBalanceService)(nil).GetBalance), ctx, userID)
	return &MockBalanceServiceGetBalanceCall{Call: call}
}

// MockBalanceServiceGetBalanceCall wrap *gomock.Call
type MockBalanceServiceGetBalanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceServiceGetBalanceCall) Return(arg0 float64, arg1 error) *MockBalanceServiceGetBalanceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceServiceGetBalanceCall) Do(f func(context.Context, domain.UserID) (float64, error)) *MockBalanceServiceGetBalanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceServiceGetBalanceCall) DoAndReturn(f func(context.Context, domain.UserID) (float64, error)) *MockBalanceServiceGetBalanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTotalAmountWithdrawn mocks base method.
func (m *MockBalanceService) GetTotalAmountWithdrawn(ctx context.Context, userID domain.UserID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmountWithdrawn", ctx, userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalAmountWithdrawn indicates an expected call of GetTotalAmountWithdrawn.
func (mr *MockBalanceServiceMockRecorder) GetTotalAmountWithdrawn(ctx, userID any) *MockBalanceServiceGetTotalAmountWithdrawnCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmountWithdrawn", reflect.TypeOf((*MockBalanceService)(nil).GetTotalAmountWithdrawn), ctx, userID)
	return &MockBalanceServiceGetTotalAmountWithdrawnCall{Call: call}
}

// MockBalanceServiceGetTotalAmountWithdrawnCall wrap *gomock.Call
type MockBalanceServiceGetTotalAmountWithdrawnCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceServiceGetTotalAmountWithdrawnCall) Return(arg0 float64, arg1 error) *MockBalanceServiceGetTotalAmountWithdrawnCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceServiceGetTotalAmountWithdrawnCall) Do(f func(context.Context, domain.UserID) (float64, error)) *MockBalanceServiceGetTotalAmountWithdrawnCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceServiceGetTotalAmountWithdrawnCall) DoAndReturn(f func(context.Context, domain.UserID) (float64, error)) *MockBalanceServiceGetTotalAmountWithdrawnCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetWithdrawalTransactions mocks base method.
func (m *MockBalanceService) GetWithdrawalTransactions(ctx context.Context, userID domain.UserID) ([]domain.WithdrawalTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalTransactions", ctx, userID)
	ret0, _ := ret[0].([]domain.WithdrawalTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalTransactions indicates an expected call of GetWithdrawalTransactions.
func (mr *MockBalanceServiceMockRecorder) GetWithdrawalTransactions(ctx, userID any) *MockBalanceServiceGetWithdrawalTransactionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalTransactions", reflect.TypeOf((*MockBalanceService)(nil).GetWithdrawalTransactions), ctx, userID)
	return &MockBalanceServiceGetWithdrawalTransactionsCall{Call: call}
}

// MockBalanceServiceGetWithdrawalTransactionsCall wrap *gomock.Call
type MockBalanceServiceGetWithdrawalTransactionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceServiceGetWithdrawalTransactionsCall) Return(arg0 []domain.WithdrawalTransaction, arg1 error) *MockBalanceServiceGetWithdrawalTransactionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceServiceGetWithdrawalTransactionsCall) Do(f func(context.Context, domain.UserID) ([]domain.WithdrawalTransaction, error)) *MockBalanceServiceGetWithdrawalTransactionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceServiceGetWithdrawalTransactionsCall) DoAndReturn(f func(context.Context, domain.UserID) ([]domain.WithdrawalTransaction, error)) *MockBalanceServiceGetWithdrawalTransactionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PayForOrderFromBalance mocks base method.
func (m *MockBalanceService) PayForOrderFromBalance(ctx context.Context, userID domain.UserID, orderID domain.OrderID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PayForOrderFromBalance", ctx, userID, orderID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// PayForOrderFromBalance indicates an expected call of PayForOrderFromBalance.
func (mr *MockBalanceServiceMockRecorder) PayForOrderFromBalance(ctx, userID, orderID, amount any) *MockBalanceServicePayForOrderFromBalanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayForOrderFromBalance", reflect.TypeOf((*MockBalanceService)(nil).PayForOrderFromBalance), ctx, userID, orderID, amount)
	return &MockBalanceServicePayForOrderFromBalanceCall{Call: call}
}

// MockBalanceServicePayForOrderFromBalanceCall wrap *gomock.Call
type MockBalanceServicePayForOrderFromBalanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceServicePayForOrderFromBalanceCall) Return(arg0 error) *MockBalanceServicePayForOrderFromBalanceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceServicePayForOrderFromBalanceCall) Do(f func(context.Context, domain.UserID, domain.OrderID, float64) error) *MockBalanceServicePayForOrderFromBalanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceServicePayForOrderFromBalanceCall) DoAndReturn(f func(context.Context, domain.UserID, domain.OrderID, float64) error) *MockBalanceServicePayForOrderFromBalanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
