// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-gophermart/internal/gophermart/handler (interfaces: TokenService)
//
// Generated by this command:
//
//	mockgen -typed -destination=../../test/mocks/gophermart/handler/token_service.go -package=mocks github.com/bq2cd/yp-go-gophermart/internal/gophermart/handler TokenService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bq2cd/yp-go-gophermart/internal/gophermart/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// IssueToken mocks base method.
func (m *MockTokenService) IssueToken(ctx context.Context, userID domain.UserID) (domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueToken", ctx, userID)
	ret0, _ := ret[0].(domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueToken indicates an expected call of IssueToken.
func (mr *MockTokenServiceMockRecorder) IssueToken(ctx, userID any) *MockTokenServiceIssueTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueToken", reflect.TypeOf((*MockTokenService)(nil).IssueToken), ctx, userID)
	return &MockTokenServiceIssueTokenCall{Call: call}
}

// MockTokenServiceIssueTokenCall wrap *gomock.Call
type MockTokenServiceIssueTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceIssueTokenCall) Return(arg0 domain.Token, arg1 error) *MockTokenServiceIssueTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceIssueTokenCall) Do(f func(context.Context, domain.UserID) (domain.Token, error)) *MockTokenServiceIssueTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceIssueTokenCall) DoAndReturn(f func(context.Context, domain.UserID) (domain.Token, error)) *MockTokenServiceIssueTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ValidateToken mocks base method.
func (m *MockTokenService) ValidateToken(ctx context.Context, token domain.Token) (domain.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(domain.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTokenServiceMockRecorder) ValidateToken(ctx, token any) *MockTokenServiceValidateTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTokenService)(nil).ValidateToken), ctx, token)
	return &MockTokenServiceValidateTokenCall{Call: call}
}

// MockTokenServiceValidateTokenCall wrap *gomock.Call
type MockTokenServiceValidateTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceValidateTokenCall) Return(arg0 domain.UserID, arg1 error) *MockTokenServiceValidateTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceValidateTokenCall) Do(f func(context.Context, domain.Token) (domain.UserID, error)) *MockTokenServiceValidateTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceValidateTokenCall) DoAndReturn(f func(context.Context, domain.Token) (domain.UserID, error)) *MockTokenServiceValidateTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
