// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-gophermart/internal/gophermart/handler (interfaces: UserService)
//
// Generated by this command:
//
//	mockgen -typed -destination=../../test/mocks/gophermart/handler/user_service.go -package=mocks github.com/bq2cd/yp-go-gophermart/internal/gophermart/handler UserService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bq2cd/yp-go-gophermart/internal/gophermart/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockUserService) Authenticate(ctx context.Context, userID domain.UserID, passwordPlain domain.PasswordPlain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, userID, passwordPlain)
	ret0, _ := ret[0].(error)
	return ret0
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockUserServiceMockRecorder) Authenticate(ctx, userID, passwordPlain any) *MockUserServiceAuthenticateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockUserService)(nil).Authenticate), ctx, userID, passwordPlain)
	return &MockUserServiceAuthenticateCall{Call: call}
}

// MockUserServiceAuthenticateCall wrap *gomock.Call
type MockUserServiceAuthenticateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceAuthenticateCall) Return(arg0 error) *MockUserServiceAuthenticateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceAuthenticateCall) Do(f func(context.Context, domain.UserID, domain.PasswordPlain) error) *MockUserServiceAuthenticateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceAuthenticateCall) DoAndReturn(f func(context.Context, domain.UserID, domain.PasswordPlain) error) *MockUserServiceAuthenticateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Register mocks base method.
func (m *MockUserService) Register(ctx context.Context, userID domain.UserID, passwordPlain domain.PasswordPlain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, userID, passwordPlain)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockUserServiceMockRecorder) Register(ctx, userID, passwordPlain any) *MockUserServiceRegisterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserService)(nil).Register), ctx, userID, passwordPlain)
	return &MockUserServiceRegisterCall{Call: call}
}

// MockUserServiceRegisterCall wrap *gomock.Call
type MockUserServiceRegisterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceRegisterCall) Return(arg0 error) *MockUserServiceRegisterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceRegisterCall) Do(f func(context.Context, domain.UserID, domain.PasswordPlain) error) *MockUserServiceRegisterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceRegisterCall) DoAndReturn(f func(context.Context, domain.UserID, domain.PasswordPlain) error) *MockUserServiceRegisterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
