// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-gophermart/internal/gophermart/service (interfaces: OrderProcessor)
//
// Generated by this command:
//
//	mockgen -typed -destination=../../test/mocks/gophermart/service/order_processor.go -package=mocks github.com/bq2cd/yp-go-gophermart/internal/gophermart/service OrderProcessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/bq2cd/yp-go-gophermart/internal/gophermart/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderProcessor is a mock of OrderProcessor interface.
type MockOrderProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockOrderProcessorMockRecorder
	isgomock struct{}
}

// MockOrderProcessorMockRecorder is the mock recorder for MockOrderProcessor.
type MockOrderProcessorMockRecorder struct {
	mock *MockOrderProcessor
}

// NewMockOrderProcessor creates a new mock instance.
func NewMockOrderProcessor(ctrl *gomock.Controller) *MockOrderProcessor {
	mock := &MockOrderProcessor{ctrl: ctrl}
	mock.recorder = &MockOrderProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderProcessor) EXPECT() *MockOrderProcessorMockRecorder {
	return m.recorder
}

// NewOrderArrived mocks base method.
func (m *MockOrderProcessor) NewOrderArrived(userID domain.UserID, orderID domain.OrderID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewOrderArrived", userID, orderID)
}

// NewOrderArrived indicates an expected call of NewOrderArrived.
func (mr *MockOrderProcessorMockRecorder) NewOrderArrived(userID, orderID any) *MockOrderProcessorNewOrderArrivedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOrderArrived", reflect.TypeOf((*MockOrderProcessor)(nil).NewOrderArrived), userID, orderID)
	return &MockOrderProcessorNewOrderArrivedCall{Call: call}
}

// MockOrderProcessorNewOrderArrivedCall wrap *gomock.Call
type MockOrderProcessorNewOrderArrivedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderProcessorNewOrderArrivedCall) Return() *MockOrderProcessorNewOrderArrivedCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderProcessorNewOrderArrivedCall) Do(f func(domain.UserID, domain.OrderID)) *MockOrderProcessorNewOrderArrivedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderProcessorNewOrderArrivedCall) DoAndReturn(f func(domain.UserID, domain.OrderID)) *MockOrderProcessorNewOrderArrivedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
