// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-gophermart/internal/gophermart/service (interfaces: SecretKeyProvider)
//
// Generated by this command:
//
//	mockgen -typed -destination=../../test/mocks/gophermart/service/secret_key_provider.go -package=mocks github.com/bq2cd/yp-go-gophermart/internal/gophermart/service SecretKeyProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSecretKeyProvider is a mock of SecretKeyProvider interface.
type MockSecretKeyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSecretKeyProviderMockRecorder
	isgomock struct{}
}

// MockSecretKeyProviderMockRecorder is the mock recorder for MockSecretKeyProvider.
type MockSecretKeyProviderMockRecorder struct {
	mock *MockSecretKeyProvider
}

// NewMockSecretKeyProvider creates a new mock instance.
func NewMockSecretKeyProvider(ctrl *gomock.Controller) *MockSecretKeyProvider {
	mock := &MockSecretKeyProvider{ctrl: ctrl}
	mock.recorder = &MockSecretKeyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretKeyProvider) EXPECT() *MockSecretKeyProviderMockRecorder {
	return m.recorder
}

// GetSecretKey mocks base method.
func (m *MockSecretKeyProvider) GetSecretKey(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretKey", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretKey indicates an expected call of GetSecretKey.
func (mr *MockSecretKeyProviderMockRecorder) GetSecretKey(ctx any) *MockSecretKeyProviderGetSecretKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretKey", reflect.TypeOf((*MockSecretKeyProvider)(nil).GetSecretKey), ctx)
	return &MockSecretKeyProviderGetSecretKeyCall{Call: call}
}

// MockSecretKeyProviderGetSecretKeyCall wrap *gomock.Call
type MockSecretKeyProviderGetSecretKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretKeyProviderGetSecretKeyCall) Return(arg0 []byte, arg1 error) *MockSecretKeyProviderGetSecretKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretKeyProviderGetSecretKeyCall) Do(f func(context.Context) ([]byte, error)) *MockSecretKeyProviderGetSecretKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretKeyProviderGetSecretKeyCall) DoAndReturn(f func(context.Context) ([]byte, error)) *MockSecretKeyProviderGetSecretKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
