// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-gophermart/internal/gophermart/service (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -typed -destination=../../test/mocks/gophermart/service/user_repository.go -package=mocks github.com/bq2cd/yp-go-gophermart/internal/gophermart/service UserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bq2cd/yp-go-gophermart/internal/gophermart/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, userID domain.UserID, passwordHash domain.PasswordHash) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, userID, passwordHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, userID, passwordHash any) *MockUserRepositoryCreateUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, userID, passwordHash)
	return &MockUserRepositoryCreateUserCall{Call: call}
}

// MockUserRepositoryCreateUserCall wrap *gomock.Call
type MockUserRepositoryCreateUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryCreateUserCall) Return(arg0 bool, arg1 error) *MockUserRepositoryCreateUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryCreateUserCall) Do(f func(context.Context, domain.UserID, domain.PasswordHash) (bool, error)) *MockUserRepositoryCreateUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryCreateUserCall) DoAndReturn(f func(context.Context, domain.UserID, domain.PasswordHash) (bool, error)) *MockUserRepositoryCreateUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPasswordHash mocks base method.
func (m *MockUserRepository) GetPasswordHash(ctx context.Context, userID domain.UserID) (domain.PasswordHash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordHash", ctx, userID)
	ret0, _ := ret[0].(domain.PasswordHash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordHash indicates an expected call of GetPasswordHash.
func (mr *MockUserRepositoryMockRecorder) GetPasswordHash(ctx, userID any) *MockUserRepositoryGetPasswordHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordHash", reflect.TypeOf((*MockUserRepository)(nil).GetPasswordHash), ctx, userID)
	return &MockUserRepositoryGetPasswordHashCall{Call: call}
}

// MockUserRepositoryGetPasswordHashCall wrap *gomock.Call
type MockUserRepositoryGetPasswordHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryGetPasswordHashCall) Return(arg0 domain.PasswordHash, arg1 error) *MockUserRepositoryGetPasswordHashCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryGetPasswordHashCall) Do(f func(context.Context, domain.UserID) (domain.PasswordHash, error)) *MockUserRepositoryGetPasswordHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryGetPasswordHashCall) DoAndReturn(f func(context.Context, domain.UserID) (domain.PasswordHash, error)) *MockUserRepositoryGetPasswordHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
