// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-gophermart/internal/gophermart/service (interfaces: BalanceRepository)
//
// Generated by this command:
//
//	mockgen -typed -destination=mocks/balance_repository.go -package=mocks . BalanceRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bq2cd/yp-go-gophermart/internal/gophermart/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceRepository is a mock of BalanceRepository interface.
type MockBalanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepositoryMockRecorder
	isgomock struct{}
}

// MockBalanceRepositoryMockRecorder is the mock recorder for MockBalanceRepository.
type MockBalanceRepositoryMockRecorder struct {
	mock *MockBalanceRepository
}

// NewMockBalanceRepository creates a new mock instance.
func NewMockBalanceRepository(ctrl *gomock.Controller) *MockBalanceRepository {
	mock := &MockBalanceRepository{ctrl: ctrl}
	mock.recorder = &MockBalanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepository) EXPECT() *MockBalanceRepositoryMockRecorder {
	return m.recorder
}

// AddFunds mocks base method.
func (m *MockBalanceRepository) AddFunds(ctx context.Context, userID domain.UserID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFunds", ctx, userID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFunds indicates an expected call of AddFunds.
func (mr *MockBalanceRepositoryMockRecorder) AddFunds(ctx, userID, amount any) *MockBalanceRepositoryAddFundsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFunds", reflect.TypeOf((*MockBalanceRepository)(nil).AddFunds), ctx, userID, amount)
	return &MockBalanceRepositoryAddFundsCall{Call: call}
}

// MockBalanceRepositoryAddFundsCall wrap *gomock.Call
type MockBalanceRepositoryAddFundsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceRepositoryAddFundsCall) Return(arg0 error) *MockBalanceRepositoryAddFundsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceRepositoryAddFundsCall) Do(f func(context.Context, domain.UserID, float64) error) *MockBalanceRepositoryAddFundsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceRepositoryAddFundsCall) DoAndReturn(f func(context.Context, domain.UserID, float64) error) *MockBalanceRepositoryAddFundsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCurrentValue mocks base method.
func (m *MockBalanceRepository) GetCurrentValue(ctx context.Context, userID domain.UserID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentValue", ctx, userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentValue indicates an expected call of GetCurrentValue.
func (mr *MockBalanceRepositoryMockRecorder) GetCurrentValue(ctx, userID any) *MockBalanceRepositoryGetCurrentValueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentValue", reflect.TypeOf((*MockBalanceRepository)(nil).GetCurrentValue), ctx, userID)
	return &MockBalanceRepositoryGetCurrentValueCall{Call: call}
}

// MockBalanceRepositoryGetCurrentValueCall wrap *gomock.Call
type MockBalanceRepositoryGetCurrentValueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceRepositoryGetCurrentValueCall) Return(arg0 float64, arg1 error) *MockBalanceRepositoryGetCurrentValueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceRepositoryGetCurrentValueCall) Do(f func(context.Context, domain.UserID) (float64, error)) *MockBalanceRepositoryGetCurrentValueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceRepositoryGetCurrentValueCall) DoAndReturn(f func(context.Context, domain.UserID) (float64, error)) *MockBalanceRepositoryGetCurrentValueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetWithdrawalTransactions mocks base method.
func (m *MockBalanceRepository) GetWithdrawalTransactions(ctx context.Context, userID domain.UserID) ([]domain.WithdrawalTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalTransactions", ctx, userID)
	ret0, _ := ret[0].([]domain.WithdrawalTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalTransactions indicates an expected call of GetWithdrawalTransactions.
func (mr *MockBalanceRepositoryMockRecorder) GetWithdrawalTransactions(ctx, userID any) *MockBalanceRepositoryGetWithdrawalTransactionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalTransactions", reflect.TypeOf((*MockBalanceRepository)(nil).GetWithdrawalTransactions), ctx, userID)
	return &MockBalanceRepositoryGetWithdrawalTransactionsCall{Call: call}
}

// MockBalanceRepositoryGetWithdrawalTransactionsCall wrap *gomock.Call
type MockBalanceRepositoryGetWithdrawalTransactionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceRepositoryGetWithdrawalTransactionsCall) Return(arg0 []domain.WithdrawalTransaction, arg1 error) *MockBalanceRepositoryGetWithdrawalTransactionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceRepositoryGetWithdrawalTransactionsCall) Do(f func(context.Context, domain.UserID) ([]domain.WithdrawalTransaction, error)) *MockBalanceRepositoryGetWithdrawalTransactionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceRepositoryGetWithdrawalTransactionsCall) DoAndReturn(f func(context.Context, domain.UserID) ([]domain.WithdrawalTransaction, error)) *MockBalanceRepositoryGetWithdrawalTransactionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WithdrawFunds mocks base method.
func (m *MockBalanceRepository) WithdrawFunds(ctx context.Context, userID domain.UserID, amount float64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawFunds", ctx, userID, amount)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithdrawFunds indicates an expected call of WithdrawFunds.
func (mr *MockBalanceRepositoryMockRecorder) WithdrawFunds(ctx, userID, amount any) *MockBalanceRepositoryWithdrawFundsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawFunds", reflect.TypeOf((*MockBalanceRepository)(nil).WithdrawFunds), ctx, userID, amount)
	return &MockBalanceRepositoryWithdrawFundsCall{Call: call}
}

// MockBalanceRepositoryWithdrawFundsCall wrap *gomock.Call
type MockBalanceRepositoryWithdrawFundsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceRepositoryWithdrawFundsCall) Return(arg0 bool, arg1 error) *MockBalanceRepositoryWithdrawFundsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceRepositoryWithdrawFundsCall) Do(f func(context.Context, domain.UserID, float64) (bool, error)) *MockBalanceRepositoryWithdrawFundsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceRepositoryWithdrawFundsCall) DoAndReturn(f func(context.Context, domain.UserID, float64) (bool, error)) *MockBalanceRepositoryWithdrawFundsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
