// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-gophermart/internal/gophermart/service (interfaces: OrderProcessor)
//
// Generated by this command:
//
//	mockgen -typed -destination=mocks/order_processor.go -package=mocks . OrderProcessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/bq2cd/yp-go-gophermart/internal/gophermart/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderProcessor is a mock of OrderProcessor interface.
type MockOrderProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockOrderProcessorMockRecorder
	isgomock struct{}
}

// MockOrderProcessorMockRecorder is the mock recorder for MockOrderProcessor.
type MockOrderProcessorMockRecorder struct {
	mock *MockOrderProcessor
}

// NewMockOrderProcessor creates a new mock instance.
func NewMockOrderProcessor(ctrl *gomock.Controller) *MockOrderProcessor {
	mock := &MockOrderProcessor{ctrl: ctrl}
	mock.recorder = &MockOrderProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderProcessor) EXPECT() *MockOrderProcessorMockRecorder {
	return m.recorder
}

// EnqueueOrder mocks base method.
func (m *MockOrderProcessor) EnqueueOrder(userID domain.UserID, orderID domain.OrderID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueOrder", userID, orderID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnqueueOrder indicates an expected call of EnqueueOrder.
func (mr *MockOrderProcessorMockRecorder) EnqueueOrder(userID, orderID any) *MockOrderProcessorEnqueueOrderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueOrder", reflect.TypeOf((*MockOrderProcessor)(nil).EnqueueOrder), userID, orderID)
	return &MockOrderProcessorEnqueueOrderCall{Call: call}
}

// MockOrderProcessorEnqueueOrderCall wrap *gomock.Call
type MockOrderProcessorEnqueueOrderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderProcessorEnqueueOrderCall) Return(arg0 bool) *MockOrderProcessorEnqueueOrderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderProcessorEnqueueOrderCall) Do(f func(domain.UserID, domain.OrderID) bool) *MockOrderProcessorEnqueueOrderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderProcessorEnqueueOrderCall) DoAndReturn(f func(domain.UserID, domain.OrderID) bool) *MockOrderProcessorEnqueueOrderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
