// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-gophermart/internal/gophermart/service (interfaces: OrderRepository)
//
// Generated by this command:
//
//	mockgen -typed -destination=mocks/order_repository.go -package=mocks . OrderRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bq2cd/yp-go-gophermart/internal/gophermart/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderRepository) CreateOrder(ctx context.Context, userID domain.UserID, orderID domain.OrderID) (bool, domain.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userID, orderID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(domain.UserID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderRepositoryMockRecorder) CreateOrder(ctx, userID, orderID any) *MockOrderRepositoryCreateOrderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderRepository)(nil).CreateOrder), ctx, userID, orderID)
	return &MockOrderRepositoryCreateOrderCall{Call: call}
}

// MockOrderRepositoryCreateOrderCall wrap *gomock.Call
type MockOrderRepositoryCreateOrderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryCreateOrderCall) Return(arg0 bool, arg1 domain.UserID, arg2 error) *MockOrderRepositoryCreateOrderCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryCreateOrderCall) Do(f func(context.Context, domain.UserID, domain.OrderID) (bool, domain.UserID, error)) *MockOrderRepositoryCreateOrderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryCreateOrderCall) DoAndReturn(f func(context.Context, domain.UserID, domain.OrderID) (bool, domain.UserID, error)) *MockOrderRepositoryCreateOrderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOrderAccruals mocks base method.
func (m *MockOrderRepository) GetOrderAccruals(ctx context.Context, userID domain.UserID, orderIDs []domain.OrderID) (map[domain.OrderID]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderAccruals", ctx, userID, orderIDs)
	ret0, _ := ret[0].(map[domain.OrderID]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderAccruals indicates an expected call of GetOrderAccruals.
func (mr *MockOrderRepositoryMockRecorder) GetOrderAccruals(ctx, userID, orderIDs any) *MockOrderRepositoryGetOrderAccrualsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderAccruals", reflect.TypeOf((*MockOrderRepository)(nil).GetOrderAccruals), ctx, userID, orderIDs)
	return &MockOrderRepositoryGetOrderAccrualsCall{Call: call}
}

// MockOrderRepositoryGetOrderAccrualsCall wrap *gomock.Call
type MockOrderRepositoryGetOrderAccrualsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryGetOrderAccrualsCall) Return(arg0 map[domain.OrderID]float64, arg1 error) *MockOrderRepositoryGetOrderAccrualsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryGetOrderAccrualsCall) Do(f func(context.Context, domain.UserID, []domain.OrderID) (map[domain.OrderID]float64, error)) *MockOrderRepositoryGetOrderAccrualsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryGetOrderAccrualsCall) DoAndReturn(f func(context.Context, domain.UserID, []domain.OrderID) (map[domain.OrderID]float64, error)) *MockOrderRepositoryGetOrderAccrualsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOrders mocks base method.
func (m *MockOrderRepository) GetOrders(ctx context.Context, userID domain.UserID) ([]domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, userID)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockOrderRepositoryMockRecorder) GetOrders(ctx, userID any) *MockOrderRepositoryGetOrdersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockOrderRepository)(nil).GetOrders), ctx, userID)
	return &MockOrderRepositoryGetOrdersCall{Call: call}
}

// MockOrderRepositoryGetOrdersCall wrap *gomock.Call
type MockOrderRepositoryGetOrdersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryGetOrdersCall) Return(arg0 []domain.Order, arg1 error) *MockOrderRepositoryGetOrdersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryGetOrdersCall) Do(f func(context.Context, domain.UserID) ([]domain.Order, error)) *MockOrderRepositoryGetOrdersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryGetOrdersCall) DoAndReturn(f func(context.Context, domain.UserID) ([]domain.Order, error)) *MockOrderRepositoryGetOrdersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
