// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-gophermart/internal/gophermart/service (interfaces: OrderProcessor)
//
// Generated by this command:
//
//	mockgen -typed -destination=mocks/order_processor.go -package=mocks . OrderProcessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bq2cd/yp-go-gophermart/internal/gophermart/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderProcessor is a mock of OrderProcessor interface.
type MockOrderProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockOrderProcessorMockRecorder
	isgomock struct{}
}

// MockOrderProcessorMockRecorder is the mock recorder for MockOrderProcessor.
type MockOrderProcessorMockRecorder struct {
	mock *MockOrderProcessor
}

// NewMockOrderProcessor creates a new mock instance.
func NewMockOrderProcessor(ctrl *gomock.Controller) *MockOrderProcessor {
	mock := &MockOrderProcessor{ctrl: ctrl}
	mock.recorder = &MockOrderProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderProcessor) EXPECT() *MockOrderProcessorMockRecorder {
	return m.recorder
}

// EnqueueOrder mocks base method.
func (m *MockOrderProcessor) EnqueueOrder(ctx context.Context, userID domain.UserID, orderID domain.OrderID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnqueueOrder", ctx, userID, orderID)
}

// EnqueueOrder indicates an expected call of EnqueueOrder.
func (mr *MockOrderProcessorMockRecorder) EnqueueOrder(ctx, userID, orderID any) *MockOrderProcessorEnqueueOrderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueOrder", reflect.TypeOf((*MockOrderProcessor)(nil).EnqueueOrder), ctx, userID, orderID)
	return &MockOrderProcessorEnqueueOrderCall{Call: call}
}

// MockOrderProcessorEnqueueOrderCall wrap *gomock.Call
type MockOrderProcessorEnqueueOrderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderProcessorEnqueueOrderCall) Return() *MockOrderProcessorEnqueueOrderCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderProcessorEnqueueOrderCall) Do(f func(context.Context, domain.UserID, domain.OrderID)) *MockOrderProcessorEnqueueOrderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderProcessorEnqueueOrderCall) DoAndReturn(f func(context.Context, domain.UserID, domain.OrderID)) *MockOrderProcessorEnqueueOrderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
