// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-gophermart/internal/gophermart/handler (interfaces: OrderService)
//
// Generated by this command:
//
//	mockgen -typed -destination=mocks/order_service.go -package=mocks . OrderService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bq2cd/yp-go-gophermart/internal/gophermart/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
	isgomock struct{}
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderService) CreateOrder(ctx context.Context, userID domain.UserID, orderID domain.OrderID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userID, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderServiceMockRecorder) CreateOrder(ctx, userID, orderID any) *MockOrderServiceCreateOrderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderService)(nil).CreateOrder), ctx, userID, orderID)
	return &MockOrderServiceCreateOrderCall{Call: call}
}

// MockOrderServiceCreateOrderCall wrap *gomock.Call
type MockOrderServiceCreateOrderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceCreateOrderCall) Return(arg0 error) *MockOrderServiceCreateOrderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceCreateOrderCall) Do(f func(context.Context, domain.UserID, domain.OrderID) error) *MockOrderServiceCreateOrderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceCreateOrderCall) DoAndReturn(f func(context.Context, domain.UserID, domain.OrderID) error) *MockOrderServiceCreateOrderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAccruals mocks base method.
func (m *MockOrderService) GetAccruals(ctx context.Context, userID domain.UserID, orderIDs []domain.OrderID) (map[domain.OrderID]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccruals", ctx, userID, orderIDs)
	ret0, _ := ret[0].(map[domain.OrderID]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccruals indicates an expected call of GetAccruals.
func (mr *MockOrderServiceMockRecorder) GetAccruals(ctx, userID, orderIDs any) *MockOrderServiceGetAccrualsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccruals", reflect.TypeOf((*MockOrderService)(nil).GetAccruals), ctx, userID, orderIDs)
	return &MockOrderServiceGetAccrualsCall{Call: call}
}

// MockOrderServiceGetAccrualsCall wrap *gomock.Call
type MockOrderServiceGetAccrualsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceGetAccrualsCall) Return(arg0 map[domain.OrderID]float64, arg1 error) *MockOrderServiceGetAccrualsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceGetAccrualsCall) Do(f func(context.Context, domain.UserID, []domain.OrderID) (map[domain.OrderID]float64, error)) *MockOrderServiceGetAccrualsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceGetAccrualsCall) DoAndReturn(f func(context.Context, domain.UserID, []domain.OrderID) (map[domain.OrderID]float64, error)) *MockOrderServiceGetAccrualsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOrders mocks base method.
func (m *MockOrderService) GetOrders(ctx context.Context, userID domain.UserID) ([]domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, userID)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockOrderServiceMockRecorder) GetOrders(ctx, userID any) *MockOrderServiceGetOrdersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockOrderService)(nil).GetOrders), ctx, userID)
	return &MockOrderServiceGetOrdersCall{Call: call}
}

// MockOrderServiceGetOrdersCall wrap *gomock.Call
type MockOrderServiceGetOrdersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceGetOrdersCall) Return(arg0 []domain.Order, arg1 error) *MockOrderServiceGetOrdersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceGetOrdersCall) Do(f func(context.Context, domain.UserID) ([]domain.Order, error)) *MockOrderServiceGetOrdersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceGetOrdersCall) DoAndReturn(f func(context.Context, domain.UserID) ([]domain.Order, error)) *MockOrderServiceGetOrdersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
